"""
{{ project_name }} - Production-grade CRUD microservice.

A RESTful API service built with FastAPI, PostgreSQL, and asyncpg.

Architecture:
- Domain-driven design with clear separation of concerns
- Repository pattern for data access abstraction
- Dependency injection for testability
- Async/await for high concurrency

Key Features:
- Full CRUD operations with pagination
- Soft delete support
- Multi-tenancy ready
- OpenAPI documentation
- Structured logging
- Health checks
- CORS support

Usage:
    # Development
    python main.py
    
    # Production
    uvicorn main:app --host 0.0.0.0 --port 8000 --workers 4
    
    # With Gunicorn
    gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker

API Endpoints:
    POST   /{{ endpoint_prefix }}/              - Create item
    GET    /{{ endpoint_prefix }}/{id}          - Get item by ID
    GET    /{{ endpoint_prefix }}/              - List items (paginated)
    GET    /{{ endpoint_prefix }}/search/       - Search items by name
    PUT    /{{ endpoint_prefix }}/{id}          - Update item
    DELETE /{{ endpoint_prefix }}/{id}          - Delete item
    POST   /{{ endpoint_prefix }}/{id}/restore  - Restore deleted item
    GET    /{{ endpoint_prefix }}/stats/count   - Count items
    GET    /health                               - Health check
    GET    /docs                                 - OpenAPI documentation

Environment Variables:
    DATABASE_URL         - PostgreSQL connection URL (required)
    ENVIRONMENT          - Deployment environment (development/staging/production)
    LOG_LEVEL            - Logging level (DEBUG/INFO/WARNING/ERROR)
    CORS_ORIGINS         - Allowed CORS origins
    
    See config/.env.example for full configuration options.

Extensions:
    To add authentication:
        1. Implement api/dependencies.py::get_current_user()
        2. Add Depends(require_auth) to protected routes
    
    To enable multi-tenancy:
        1. Set ENABLE_MULTI_TENANCY=true
        2. Pass X-Tenant-ID header in requests
    
    To add custom validation:
        1. Extend models/domain.py business logic
        2. Add validators in models/schemas.py
    
    To add new endpoints:
        1. Add methods to repository/interface.py
        2. Implement in repository/postgres.py
        3. Add routes in api/routes.py

Database Setup:
    1. Create PostgreSQL database
    2. Run migrations: psql -U user -d dbname -f migrations.sql
    3. Set DATABASE_URL environment variable
    4. Start application

For more details, see README.md
"""

__version__ = "1.0.0"
__author__ = "Generated by Namel3ss"

from main import app

__all__ = ["app"]
