"""
Tests for namel3ss.deps.generator module.

Tests dependency file generation with non-destructive updates.
"""

import pytest
import json
from pathlib import Path
from namel3ss.deps.generator import DependencyGenerator, GeneratedDeps
from namel3ss.deps.spec import PythonPackage, NPMPackage


class TestGeneratedDeps:
    """Test GeneratedDeps dataclass"""
    
    def test_generated_deps_creation(self):
        """Test creating GeneratedDeps"""
        deps = GeneratedDeps(
            requirements_txt="fastapi>=0.110",
            package_json='{"name": "test"}',
            added_python=["fastapi"],
            added_npm=["react"],
        )
        
        assert "fastapi" in deps.requirements_txt
        assert "test" in deps.package_json
        assert len(deps.added_python) == 1
        assert len(deps.added_npm) == 1


class TestDependencyGenerator:
    """Test DependencyGenerator class"""
    
    def test_generator_creation(self):
        """Test creating a DependencyGenerator"""
        generator = DependencyGenerator()
        assert generator is not None
    
    def test_generate_empty_packages(self):
        """Test generating with no packages"""
        generator = DependencyGenerator()
        result = generator.generate([], [])
        
        assert result.requirements_txt is not None
        assert result.package_json is not None
        assert len(result.added_python) == 0
        assert len(result.added_npm) == 0
    
    def test_generate_python_only(self):
        """Test generating with Python packages only"""
        generator = DependencyGenerator()
        python_pkgs = [
            PythonPackage("fastapi", ">=0.110,<1.0"),
            PythonPackage("pydantic", ">=2.7,<3.0"),
        ]
        
        result = generator.generate(python_pkgs, [])
        
        assert "fastapi" in result.requirements_txt
        assert "pydantic" in result.requirements_txt
        assert len(result.added_python) == 2
        assert "fastapi" in result.added_python
    
    def test_generate_npm_only(self):
        """Test generating with NPM packages only"""
        generator = DependencyGenerator()
        npm_pkgs = [
            NPMPackage("react", "^18.2.0", dev=False),
            NPMPackage("react-dom", "^18.2.0", dev=False),
        ]
        
        result = generator.generate([], npm_pkgs)
        
        pkg_json = json.loads(result.package_json)
        assert "react" in pkg_json["dependencies"]
        assert "react-dom" in pkg_json["dependencies"]
        assert len(result.added_npm) == 2
    
    def test_generate_both_python_and_npm(self):
        """Test generating with both Python and NPM packages"""
        generator = DependencyGenerator()
        python_pkgs = [PythonPackage("fastapi", ">=0.110")]
        npm_pkgs = [NPMPackage("react", "^18.2.0", dev=False)]
        
        result = generator.generate(python_pkgs, npm_pkgs)
        
        assert "fastapi" in result.requirements_txt
        pkg_json = json.loads(result.package_json)
        assert "react" in pkg_json["dependencies"]


class TestRequirementsTxtGeneration:
    """Test requirements.txt generation"""
    
    def test_requirements_txt_format(self):
        """Test requirements.txt format"""
        generator = DependencyGenerator()
        python_pkgs = [
            PythonPackage("fastapi", ">=0.110,<1.0"),
            PythonPackage("pydantic", ">=2.7,<3.0"),
        ]
        
        result = generator.generate(python_pkgs, [])
        
        # Should have header comment
        assert "Generated by namel3ss sync-deps" in result.requirements_txt
        
        # Should have packages with versions
        assert "fastapi>=0.110,<1.0" in result.requirements_txt
        assert "pydantic>=2.7,<3.0" in result.requirements_txt
    
    def test_requirements_txt_alphabetical(self):
        """Test that requirements.txt is alphabetically sorted"""
        generator = DependencyGenerator()
        python_pkgs = [
            PythonPackage("zulu", "1.0"),
            PythonPackage("alpha", "1.0"),
            PythonPackage("beta", "1.0"),
        ]
        
        result = generator.generate(python_pkgs, [])
        lines = [l for l in result.requirements_txt.split('\n') if l and not l.startswith('#')]
        
        # Check alphabetical order
        assert lines[0].startswith("alpha")
        assert lines[1].startswith("beta")
        assert lines[2].startswith("zulu")
    
    def test_requirements_txt_no_version(self):
        """Test package without version constraint"""
        generator = DependencyGenerator()
        python_pkgs = [PythonPackage("some-package", "")]
        
        result = generator.generate(python_pkgs, [])
        
        assert "some-package" in result.requirements_txt


class TestPackageJsonGeneration:
    """Test package.json generation"""
    
    def test_package_json_format(self):
        """Test package.json format"""
        generator = DependencyGenerator()
        npm_pkgs = [
            NPMPackage("react", "^18.2.0", dev=False),
            NPMPackage("typescript", "^5.0.0", dev=True),
        ]
        
        result = generator.generate([], npm_pkgs)
        pkg_json = json.loads(result.package_json)
        
        # Should have standard fields
        assert "name" in pkg_json
        assert "version" in pkg_json
        assert "dependencies" in pkg_json
        assert "devDependencies" in pkg_json
        
        # Should have packages in correct sections
        assert "react" in pkg_json["dependencies"]
        assert "typescript" in pkg_json["devDependencies"]
    
    def test_package_json_dev_vs_regular(self):
        """Test separation of dev and regular dependencies"""
        generator = DependencyGenerator()
        npm_pkgs = [
            NPMPackage("react", "^18.2.0", dev=False),
            NPMPackage("react-dom", "^18.2.0", dev=False),
            NPMPackage("typescript", "^5.0.0", dev=True),
            NPMPackage("vite", "^5.0.0", dev=True),
        ]
        
        result = generator.generate([], npm_pkgs)
        pkg_json = json.loads(result.package_json)
        
        assert len(pkg_json["dependencies"]) == 2
        assert len(pkg_json["devDependencies"]) == 2
    
    def test_package_json_alphabetical(self):
        """Test that package.json dependencies are alphabetically sorted"""
        generator = DependencyGenerator()
        npm_pkgs = [
            NPMPackage("zulu", "1.0.0", dev=False),
            NPMPackage("alpha", "1.0.0", dev=False),
            NPMPackage("beta", "1.0.0", dev=False),
        ]
        
        result = generator.generate([], npm_pkgs)
        pkg_json = json.loads(result.package_json)
        
        deps_keys = list(pkg_json["dependencies"].keys())
        assert deps_keys == ["alpha", "beta", "zulu"]


class TestNonDestructiveUpdates:
    """Test non-destructive update behavior"""
    
    def test_preserve_existing_python_packages(self):
        """Test that existing Python packages are preserved"""
        import tempfile
        with tempfile.TemporaryDirectory() as tmpdir:
            req_file = Path(tmpdir) / "requirements.txt"
            req_file.write_text("custom-package==1.0.0\nfastapi>=0.100\n", encoding='utf-8')
            
            generator = DependencyGenerator()
            python_pkgs = [PythonPackage("pydantic", ">=2.7")]
            
            result = generator.generate(python_pkgs, [], existing_requirements_path=req_file)
            
            # Should preserve custom package
            assert "custom-package==1.0.0" in result.requirements_txt
            # Should add new package
            assert "pydantic" in result.requirements_txt
            # Existing package should be preserved
            assert "fastapi" in result.requirements_txt
    
    def test_preserve_existing_npm_packages(self):
        """Test that existing NPM packages are preserved"""
        import tempfile
        with tempfile.TemporaryDirectory() as tmpdir:
            pkg_file = Path(tmpdir) / "package.json"
            existing_pkg = {
                "name": "my-app",
                "version": "1.0.0",
                "dependencies": {
                    "custom-lib": "^1.0.0",
                    "react": "^18.0.0"
                },
                "devDependencies": {}
            }
            pkg_file.write_text(json.dumps(existing_pkg, indent=2), encoding='utf-8')
            
            generator = DependencyGenerator()
            npm_pkgs = [NPMPackage("axios", "^1.0.0", dev=False)]
            
            result = generator.generate([], npm_pkgs, existing_package_json_path=pkg_file)
            pkg_json = json.loads(result.package_json)
            
            # Should preserve custom package
            assert "custom-lib" in pkg_json["dependencies"]
            # Should preserve existing package
            assert "react" in pkg_json["dependencies"]
            # Should add new package
            assert "axios" in pkg_json["dependencies"]
    
    def test_preserve_user_version_pins(self):
        """Test that user version pins are preserved"""
        import tempfile
        with tempfile.TemporaryDirectory() as tmpdir:
            req_file = Path(tmpdir) / "requirements.txt"
            # User has pinned fastapi to specific version
            req_file.write_text("fastapi==0.109.0\n", encoding='utf-8')
            
            generator = DependencyGenerator()
            # We try to add fastapi with different version
            python_pkgs = [PythonPackage("fastapi", ">=0.110,<1.0")]
            
            result = generator.generate(python_pkgs, [], existing_requirements_path=req_file)
            
            # Should preserve user's version pin
            assert "fastapi==0.109.0" in result.requirements_txt
            # Should NOT have our version
            assert "fastapi>=0.110" not in result.requirements_txt


class TestFileWriting:
    """Test writing to files"""
    
    def test_generate_requirements_file(self):
        """Test writing requirements.txt to file"""
        import tempfile
        with tempfile.TemporaryDirectory() as tmpdir:
            output_file = Path(tmpdir) / "requirements.txt"
            
            generator = DependencyGenerator()
            python_pkgs = [PythonPackage("fastapi", ">=0.110")]
            
            generator.generate_requirements_file(python_pkgs, output_file)
            
            assert output_file.exists()
            content = output_file.read_text(encoding='utf-8')
            assert "fastapi" in content
    
    def test_generate_package_json_file(self):
        """Test writing package.json to file"""
        import tempfile
        with tempfile.TemporaryDirectory() as tmpdir:
            output_file = Path(tmpdir) / "package.json"
            
            generator = DependencyGenerator()
            npm_pkgs = [NPMPackage("react", "^18.2.0", dev=False)]
            
            generator.generate_package_json_file(npm_pkgs, output_file)
            
            assert output_file.exists()
            content = output_file.read_text(encoding='utf-8')
            pkg_json = json.loads(content)
            assert "react" in pkg_json["dependencies"]
    
    def test_overwrite_existing_file(self):
        """Test overwriting existing files"""
        import tempfile
        with tempfile.TemporaryDirectory() as tmpdir:
            output_file = Path(tmpdir) / "requirements.txt"
            output_file.write_text("old-package==1.0.0\n", encoding='utf-8')
            
            generator = DependencyGenerator()
            python_pkgs = [PythonPackage("fastapi", ">=0.110")]
            
            generator.generate_requirements_file(python_pkgs, output_file, existing_path=output_file)
            
            content = output_file.read_text(encoding='utf-8')
            # Should preserve old package
            assert "old-package" in content
            # Should add new package
            assert "fastapi" in content


class TestEdgeCases:
    """Test edge cases"""
    
    def test_empty_existing_requirements(self):
        """Test with empty existing requirements.txt"""
        import tempfile
        with tempfile.TemporaryDirectory() as tmpdir:
            req_file = Path(tmpdir) / "requirements.txt"
            req_file.write_text("", encoding='utf-8')
            
            generator = DependencyGenerator()
            python_pkgs = [PythonPackage("fastapi", ">=0.110")]
            
            result = generator.generate(python_pkgs, [], existing_requirements_path=req_file)
            
            assert "fastapi" in result.requirements_txt
    
    def test_malformed_package_json(self):
        """Test with malformed existing package.json"""
        import tempfile
        with tempfile.TemporaryDirectory() as tmpdir:
            pkg_file = Path(tmpdir) / "package.json"
            pkg_file.write_text("{ malformed json", encoding='utf-8')
            
            generator = DependencyGenerator()
            npm_pkgs = [NPMPackage("react", "^18.2.0", dev=False)]
            
            # Should handle gracefully and create new package.json
            result = generator.generate([], npm_pkgs, existing_package_json_path=pkg_file)
            
            pkg_json = json.loads(result.package_json)
            assert "react" in pkg_json["dependencies"]
    
    def test_duplicate_packages(self):
        """Test with duplicate packages in input"""
        generator = DependencyGenerator()
        python_pkgs = [
            PythonPackage("fastapi", ">=0.110"),
            PythonPackage("fastapi", ">=0.110"),  # Duplicate
        ]
        
        result = generator.generate(python_pkgs, [])
        
        # Should deduplicate
        lines = [l for l in result.requirements_txt.split('\n') if l.startswith("fastapi")]
        assert len(lines) == 1


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
