"""
Backend entrypoint for Namel3ss application.

This file is automatically generated by `namel3ss init` and serves as
the FastAPI application entry point.
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

# Import Namel3ss runtime (will be generated from .ai file)
# from .generated import app as n3_app

app = FastAPI(
    title="Namel3ss App",
    description="Generated by Namel3ss",
    version="0.1.0"
)

# CORS configuration for frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173"],  # Vite default port
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
async def root():
    """Health check endpoint"""
    return {"status": "ok", "message": "Namel3ss backend running"}

@app.get("/health")
async def health():
    """Health check for monitoring"""
    return {"status": "healthy"}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
