"""
namel3ss init - Project Scaffolding Command

Creates a new Namel3ss project with a complete, ready-to-run structure.

Features:
- Opinionated project layout
- Starter .ai app with realistic example
- Backend scaffolding (FastAPI)
- Frontend scaffolding (React + Vite)
- Automatic dependency generation via sync-deps
"""

import sys
from pathlib import Path
from typing import Optional
import shutil

from namel3ss.deps import DependencyManager


# =============================================================================
# Output Helper
# =============================================================================

def safe_print(msg: str) -> None:
    """Print message, handling Unicode errors gracefully"""
    try:
        print(msg)
    except UnicodeEncodeError:
        # Strip emojis and special characters for Windows compatibility
        print(msg.encode('ascii', 'ignore').decode('ascii'))


# =============================================================================
# Default Project Files
# =============================================================================

DEFAULT_APP_AI = '''# Welcome to Your Namel3ss App!
# This is a starter application showcasing core features.

app "MyApp" {
    description: "A starter Namel3ss application"
}

# =============================================================================
# AI Configuration
# =============================================================================

llm gpt4 {
    provider: "openai"
    model: "gpt-4"
    temperature: 0.7
    max_tokens: 1000
}

memory conversation_history {
    type: "short_term"
    capacity: 50
}

prompt helpful_assistant {
    role: "system"
    content: "You are a helpful AI assistant. Provide clear, concise answers."
}

# =============================================================================
# Tools & Agents
# =============================================================================

tool generate_greeting {
    description: "Generate a personalized greeting"
    parameters: {
        name: {
            type: "string"
            description: "Name of the person to greet"
            required: true
        }
        language: {
            type: "string"
            description: "Language for greeting"
            enum: ["english", "spanish", "french"]
            default: "english"
        }
    }
}

agent assistant {
    llm: gpt4
    memory: conversation_history
    tools: [generate_greeting]
    goal: "Help users with their questions"
    system_prompt: helpful_assistant
    temperature: 0.7
}

# =============================================================================
# Data
# =============================================================================

dataset users from table users
dataset messages from table messages

# =============================================================================
# Pages
# =============================================================================

page "Home" at "/" {
    show text {
        content: "Welcome to your Namel3ss app!"
        size: "large"
    }
    
    show form {
        title: "Try the AI Assistant"
        agent: assistant
    }
}

page "Dashboard" at "/dashboard" {
    show text {
        content: "Dashboard Overview"
    }
    
    show data_table {
        source: users
        title: "Users"
        sortable: true
        filterable: true
    }
    
    show chart {
        type: "bar"
        title: "Activity"
        data_source: messages
    }
}

page "Chat" at "/chat" {
    show text {
        content: "Chat with AI"
    }
}
'''

DEFAULT_BACKEND_MAIN_PY = '''"""
Backend entrypoint for Namel3ss application.

This file is automatically generated by `namel3ss init` and serves as
the FastAPI application entry point.
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

# Import Namel3ss runtime (will be generated from .ai file)
# from .generated import app as n3_app

app = FastAPI(
    title="Namel3ss App",
    description="Generated by Namel3ss",
    version="0.1.0"
)

# CORS configuration for frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173"],  # Vite default port
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
async def root():
    """Health check endpoint"""
    return {"status": "ok", "message": "Namel3ss backend running"}

@app.get("/health")
async def health():
    """Health check for monitoring"""
    return {"status": "healthy"}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
'''

DEFAULT_FRONTEND_MAIN_TSX = '''import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
'''

DEFAULT_FRONTEND_APP_TSX = '''import React from 'react'

function App() {
  return (
    <div className="min-h-screen bg-gray-100">
      <header className="bg-white shadow">
        <div className="max-w-7xl mx-auto py-6 px-4">
          <h1 className="text-3xl font-bold text-gray-900">
            Namel3ss App
          </h1>
        </div>
      </header>
      <main>
        <div className="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
          <div className="px-4 py-6 sm:px-0">
            <div className="border-4 border-dashed border-gray-200 rounded-lg p-8">
              <h2 className="text-2xl font-semibold mb-4">
                Welcome to Your Namel3ss Application
              </h2>
              <p className="text-gray-600 mb-4">
                This is a starter frontend for your Namel3ss app.
              </p>
              <div className="space-y-2">
                <p className="text-sm text-gray-500">
                  📝 Edit <code className="bg-gray-200 px-2 py-1 rounded">app.ai</code> to modify your application
                </p>
                <p className="text-sm text-gray-500">
                  🔄 Run <code className="bg-gray-200 px-2 py-1 rounded">namel3ss build</code> to generate backend/frontend
                </p>
                <p className="text-sm text-gray-500">
                  🚀 Run <code className="bg-gray-200 px-2 py-1 rounded">namel3ss run</code> to start development server
                </p>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}

export default App
'''

DEFAULT_FRONTEND_INDEX_CSS = '''@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  font-family: Inter, system-ui, Avenir, Helvetica, Arial, sans-serif;
  line-height: 1.5;
  font-weight: 400;
}

body {
  margin: 0;
  min-width: 320px;
  min-height: 100vh;
}
'''

DEFAULT_VITE_CONFIG = '''import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  server: {
    port: 5173,
    proxy: {
      '/api': {
        target: 'http://localhost:8000',
        changeOrigin: true,
      },
    },
  },
})
'''

DEFAULT_TSCONFIG_JSON = '''{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,

    /* Bundler mode */
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",

    /* Linting */
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true
  },
  "include": ["src"],
  "references": [{ "path": "./tsconfig.node.json" }]
}
'''

DEFAULT_TSCONFIG_NODE_JSON = '''{
  "compilerOptions": {
    "composite": true,
    "skipLibCheck": true,
    "module": "ESNext",
    "moduleResolution": "bundler",
    "allowSyntheticDefaultImports": true
  },
  "include": ["vite.config.ts"]
}
'''

DEFAULT_INDEX_HTML = '''<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Namel3ss App</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
'''

DEFAULT_GITIGNORE = '''# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg
venv/
env/
.venv

# Node
node_modules/
dist/
.cache/

# IDEs
.vscode/
.idea/
*.swp
*.swo
*~

# OS
.DS_Store
Thumbs.db

# Env
.env
.env.local

# Namel3ss
backend_build/
frontend_build/
.namel3ss/
'''

DEFAULT_ENV_EXAMPLE = '''# Backend Configuration
DATABASE_URL=postgresql://user:password@localhost:5432/dbname
SECRET_KEY=your-secret-key-here

# AI Provider Keys
OPENAI_API_KEY=your-openai-key
ANTHROPIC_API_KEY=your-anthropic-key

# Server Configuration
HOST=0.0.0.0
PORT=8000
RELOAD=true
'''

DEFAULT_README_MD = '''# {project_name}

A Namel3ss application.

## Getting Started

### Prerequisites

- Python 3.10+
- Node.js 18+
- PostgreSQL (optional, for database features)

### Installation

1. Install Python dependencies:
```bash
cd backend
pip install -r requirements.txt
```

2. Install Node dependencies:
```bash
cd frontend
npm install
```

3. Set up environment variables:
```bash
cp .env.example .env
# Edit .env with your configuration
```

### Development

1. Build the application:
```bash
namel3ss build app.ai
```

2. Run the development server:
```bash
namel3ss run app.ai
```

The backend will be available at http://localhost:8000
The frontend will be available at http://localhost:5173

### Project Structure

```
{project_name}/
  app.ai                  # Main Namel3ss application definition
  backend/
    main.py              # FastAPI entrypoint
    requirements.txt     # Python dependencies
  frontend/
    src/
      App.tsx            # Main React component
      main.tsx           # React entrypoint
    package.json         # Node dependencies
    vite.config.ts       # Vite configuration
  .env.example           # Environment variable template
  README.md              # This file
```

### Updating Dependencies

After modifying `app.ai`, run:
```bash
namel3ss sync-deps
```

This will automatically update `requirements.txt` and `package.json` based on
features used in your application.

## Learn More

- [Namel3ss Documentation](https://github.com/namel3ss-Ai/namel3ss-programming-language)
- [FastAPI Documentation](https://fastapi.tiangolo.com/)
- [React Documentation](https://react.dev/)
'''


# =============================================================================
# Project Scaffolding
# =============================================================================

def cmd_init(args) -> int:
    """Execute namel3ss init command"""
    project_name = args.project_name
    force = args.force
    
    # Determine project directory
    if project_name == ".":
        project_dir = Path.cwd()
        project_name = project_dir.name
    else:
        project_dir = Path.cwd() / project_name
    
    # Check if directory exists
    if project_dir.exists() and not force:
        if any(project_dir.iterdir()):
            safe_print(f"❌ Error: Directory '{project_dir}' already exists and is not empty")
            safe_print(f"   Use --force to initialize anyway")
            return 1
    
    try:
        # Create project structure
        safe_print(f"🚀 Initializing Namel3ss project: {project_name}")
        safe_print(f"📁 Location: {project_dir}")
        
        # Create directories
        project_dir.mkdir(parents=True, exist_ok=True)
        (project_dir / "backend").mkdir(exist_ok=True)
        (project_dir / "frontend" / "src").mkdir(parents=True, exist_ok=True)
        
        # Create app.ai
        safe_print("📝 Creating app.ai...")
        (project_dir / "app.ai").write_text(DEFAULT_APP_AI, encoding='utf-8')
        
        # Create backend files
        safe_print("🐍 Setting up backend...")
        (project_dir / "backend" / "main.py").write_text(DEFAULT_BACKEND_MAIN_PY, encoding='utf-8')
        
        # Create frontend files
        safe_print("⚛️  Setting up frontend...")
        (project_dir / "frontend" / "src" / "main.tsx").write_text(DEFAULT_FRONTEND_MAIN_TSX, encoding='utf-8')
        (project_dir / "frontend" / "src" / "App.tsx").write_text(DEFAULT_FRONTEND_APP_TSX, encoding='utf-8')
        (project_dir / "frontend" / "src" / "index.css").write_text(DEFAULT_FRONTEND_INDEX_CSS, encoding='utf-8')
        (project_dir / "frontend" / "vite.config.ts").write_text(DEFAULT_VITE_CONFIG, encoding='utf-8')
        (project_dir / "frontend" / "tsconfig.json").write_text(DEFAULT_TSCONFIG_JSON, encoding='utf-8')
        (project_dir / "frontend" / "tsconfig.node.json").write_text(DEFAULT_TSCONFIG_NODE_JSON, encoding='utf-8')
        (project_dir / "frontend" / "index.html").write_text(DEFAULT_INDEX_HTML, encoding='utf-8')
        
        # Create config files
        safe_print("⚙️  Creating configuration files...")
        (project_dir / ".gitignore").write_text(DEFAULT_GITIGNORE, encoding='utf-8')
        (project_dir / ".env.example").write_text(DEFAULT_ENV_EXAMPLE, encoding='utf-8')
        
        readme_content = DEFAULT_README_MD.replace('{project_name}', project_name)
        (project_dir / "README.md").write_text(readme_content, encoding='utf-8')
        
        # Generate dependencies using sync-deps
        safe_print("📦 Generating dependencies...")
        manager = DependencyManager(verbose=False)
        result = manager.sync_project(project_dir)
        
        safe_print(f"\n✅ Project '{project_name}' created successfully!")
        safe_print(f"\n📚 Next steps:")
        safe_print(f"   cd {project_name if project_name != '.' else 'your_project'}")
        safe_print(f"   pip install -r backend/requirements.txt")
        safe_print(f"   cd frontend && npm install")
        safe_print(f"   cd .. && namel3ss run app.ai")
        
        if result['features']:
            safe_print(f"\n✨ Detected features: {', '.join(sorted(result['features']))}")
        
        return 0
        
    except Exception as e:
        safe_print(f"❌ Error creating project: {e}")
        import traceback
        traceback.print_exc()
        return 1


def add_init_command(subparsers):
    """Add init command to CLI"""
    init_parser = subparsers.add_parser(
        'init',
        help='Initialize a new Namel3ss project'
    )
    init_parser.add_argument(
        'project_name',
        nargs='?',
        default='.',
        help='Project name or "." for current directory (default: .)'
    )
    init_parser.add_argument(
        '--force',
        action='store_true',
        help='Initialize even if directory exists and is not empty'
    )
    init_parser.set_defaults(func=cmd_init)
