"""Type helpers for the Namel3ss language."""

from .core import (
	ANY_TYPE,
	AnyType,
	DatasetType,
	ExpressionType,
	FrameTypeRef,
	ListType,
	MapType,
	N3Type,
	PromptIOTypes,
	ScalarKind,
	ScalarType,
	derive_filter_schema,
	derive_group_schema,
	derive_join_schema,
	derive_select_schema,
	infer_scalar_type,
	is_assignable,
	is_compatible,
	lookup_column_type,
	stringify_type,
)
from .frame import FrameColumnType, N3FrameType
from namel3ss.errors import N3TypeError
from .checker import (
    check_app, check_module,
    check_app_with_stdlib, check_program_with_stdlib, check_module_with_stdlib,
    check_app_enhanced, check_module_enhanced,
    EnhancedAppTypeChecker
)
from .static_checker import (
    # Type system
    Type,
    PrimitiveType,
    ArrayType,
    ObjectType,
    UnionType,
    FunctionType,
    EnumType,
    AnyType as StaticAnyType,
    TEXT,
    NUMBER,
    BOOLEAN,
    NULL,
    ANY,
    # Type checker
    StaticTypeChecker,
    check_module_static,
    check_app_static,
)

__all__ = [
	"ANY_TYPE",
	"AnyType", 
	"DatasetType",
	"ExpressionType",
	"FrameTypeRef",
	"ListType",
	"MapType",
	"PromptIOTypes",
	"ScalarKind",
	"ScalarType",
	"N3Type",
	"FrameColumnType",
	"N3FrameType",
	"derive_filter_schema",
	"derive_group_schema",
	"derive_join_schema",
	"derive_select_schema",
	"infer_scalar_type",
	"is_assignable",
	"is_compatible",
	"lookup_column_type",
	"stringify_type",
	"check_app",
	"check_module",
	"N3TypeError",
	# Standard library enhanced functions
	"check_app_with_stdlib",
	"check_program_with_stdlib", 
	"check_module_with_stdlib",
	"check_app_enhanced",
	"check_module_enhanced", 
	"EnhancedAppTypeChecker",
	# Static type checking (world-class implementation)
	"Type",
	"PrimitiveType",
	"ArrayType",
	"ObjectType",
	"UnionType",
	"FunctionType",
	"EnumType",
	"StaticAnyType",
	"TEXT",
	"NUMBER",
	"BOOLEAN",
	"NULL",
	"ANY",
	"StaticTypeChecker",
	"check_module_static",
	"check_app_static",
]

